using System.Text;
using GunMix.Core.Audio;

namespace GunMix.Core.ExportTargets;

/// <summary>
/// Source 引擎（Left 4 Dead 2 / Garry's Mod）导出目标：可选项。
///
/// 格式要求（PCM 44.1 kHz / 16-bit，Source 引擎标准）：
/// 采样率经 WDL 重采样到 44.1 kHz，16 bit 量化（沿用 TPDF 抖动与取整规则）。
/// 本工具的混音是等幅复制到左右声道或原双声道，不做破坏性降混；如需 3D 空间声源可选单声道。
///
/// 附带 game_sounds 脚本：语法取自 Source SDK 2025 的 game_sounds_weapons.txt
/// （https://github.com/Yuis-Archives/source-sdk-2025），顶层条目 + channel/volume/soundlevel/pitch，
/// 单文件用 "wave"，多变体用 "rndwave" 包一组 "wave"。
/// </summary>
public static class SourceEngine
{
    /// <summary>Source 引擎标准采样率（44.1 kHz）。</summary>
    public const int SampleRate = 44100;

    /// <summary>Source 引擎标准位深（16 bit PCM）。</summary>
    public const int BitsPerSample = 16;

    /// <summary>枪声类事件的默认通道。</summary>
    public const string ChannelWeapon = "CHAN_WEAPON";

    /// <summary>装填/动作类事件的默认通道。</summary>
    public const string ChannelItem = "CHAN_ITEM";

    /// <summary>枪声类事件的默认声压级。</summary>
    public const string SoundLevelGunfire = "SNDLVL_GUNFIRE";

    /// <summary>动作类事件的默认声压级。</summary>
    public const string SoundLevelNorm = "SNDLVL_NORM";

    /// <summary>
    /// 把 48 kHz 的混音结果转成 Source 可用的 44.1 kHz 16 bit WAV。
    /// <paramref name="monoDownmix"/> 为 true 时取左右平均转单声道（Source 3D 声源的常规做法）。
    /// </summary>
    public static byte[] ToSourcePcm(
        float[] interleavedStereo, int sourceRate, int sourceChannels,
        bool monoDownmix, bool dither, int ditherSeed, double gain = 1.0)
    {
        var data = monoDownmix ? DownmixToMono(interleavedStereo, sourceChannels) : interleavedStereo;
        int channels = monoDownmix ? 1 : sourceChannels;
        if (sourceRate != SampleRate)
            data = Resampler.Resample(data, channels, sourceRate, SampleRate);
        var shorts = dither
            ? Quantizer.ToInt16(data, true, ditherSeed, gain)
            : Quantizer.ToInt16(data, false, ditherSeed, gain);
        return Quantizer.ToInt16Bytes(shorts);
    }

    private static float[] DownmixToMono(float[] interleaved, int channels)
    {
        if (channels == 1) return interleaved;
        long frames = interleaved.LongLength / channels;
        var mono = new float[frames];
        for (long f = 0; f < frames; f++)
        {
            float sum = 0;
            for (int c = 0; c < channels; c++) sum += interleaved[f * channels + c];
            mono[f] = sum / channels;
        }
        return mono;
    }

    /// <summary>一个 game_sounds 条目：事件名 → 一组文件（多文件生成 rndwave）。</summary>
    public sealed record SoundEntry(string EventName, string Channel, string Volume, string SoundLevel, string Pitch, IReadOnlyList<string> WavePaths);

    /// <summary>生成 game_sounds_*.txt（KeyValues）。路径相对游戏的 sound/ 目录。</summary>
    public static string BuildGameSounds(string weaponName, IEnumerable<SoundEntry> entries)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"// game_sounds_{SanitizeIdentifier(weaponName)}.txt");
        sb.AppendLine($"// Generated by 枪声分层工作台 {RecipeJsonVersion} for Source engine (Left 4 Dead 2 / Garry's Mod)");
        sb.AppendLine("// Paths are relative to the game's sound/ folder.");
        sb.AppendLine("// Place this file in your mod's scripts/ folder and add it to the game_sounds manifest.");
        sb.AppendLine();

        foreach (var entry in entries)
        {
            if (entry.WavePaths.Count == 0) continue;
            sb.Append('"').Append(entry.EventName).AppendLine("\"");
            sb.AppendLine("{");
            AppendField(sb, "channel", entry.Channel);
            AppendField(sb, "volume", entry.Volume);
            AppendField(sb, "soundlevel", entry.SoundLevel);
            AppendField(sb, "pitch", entry.Pitch);
            if (entry.WavePaths.Count == 1)
            {
                AppendField(sb, "wave", entry.WavePaths[0]);
            }
            else
            {
                AppendField(sb, "rndwave", null);
                sb.AppendLine("\t{");
                foreach (var w in entry.WavePaths)
                {
                    sb.Append("\t\t").Append("\"wave\"\t\t\"").Append(w).AppendLine("\"");
                }
                sb.AppendLine("\t}");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private const string RecipeJsonVersion = "0.3.0";

    private static void AppendField(StringBuilder sb, string key, string? value)
    {
        if (value == null)
        {
            sb.Append('\t').Append('"').Append(key).Append('"');
            return;
        }
        sb.Append("\t\"").Append(key).Append("\"\t\t\"").Append(value).AppendLine("\"");
    }

    /// <summary>事件名与文件名的安全化：Source 只认字母数字与下划线。</summary>
    public static string SanitizeIdentifier(string raw)
    {
        var sb = new StringBuilder(raw.Length);
        foreach (var c in raw)
        {
            if (char.IsAsciiLetterOrDigit(c) || c == '_') sb.Append(char.ToLowerInvariant(c));
            else if (c is '-' or ' ' or '.') sb.Append('_');
        }
        return sb.Length > 0 ? sb.ToString() : "weapon";
    }

    /// <summary>游戏内相对路径（sound/ 目录下的位置）。</summary>
    public static string GamePath(string weaponName, string fileName)
        => $"weapons/{SanitizeIdentifier(weaponName)}/{fileName}";
}
